#Configuracion de teclas para Argentum Forge
#Mapeo de acciones a codigos de tecla GLFW
#Sun Mar 29 00:26:29 CET 2026
DOWN=83
SHOW_OPTIONS=294
GOTO_POS=293
MAP_PROPERTIES=295
OPEN_SURFACE_EDITOR=85
TAKE_SCREENSHOT=291
TOGGLE_TRIGGERS=55
UP=87
TOGGLE_OBJECTS=57
OPEN_OBJ_EDITOR=76
CUT=88
LEFT=65
RELOAD_MAP=296
NEW_MAP=78
TOGGLE_NPCS=56
TOGGLE_VIEWPORT=297
ZOOM_IN=334
ZOOM_OUT=333
OPEN_TRIGGER_EDITOR=84
VALIDATE_MAP=298
TOGGLE_LAYER_3=51
TOGGLE_LAYER_4=52
MULTI_SELECT=340
TOGGLE_LAYER_1=49
TOGGLE_LAYER_2=50
TOOL_MAGIC_WAND=72
EXIT_GAME=256
TOOL_BRUSH=66
TOGGLE_GRID=71
TOGGLE_BLOCKS=53
DELETE=261
OPEN_NPC_EDITOR=75
TOGGLE_PHOTO_MODE=301
OPEN_PARTICLE_EDITOR=81
RIGHT=68
PASTE_ADVANCED=86
TOGGLE_WALKING_MODE=292
OPEN_MAP=79
OPEN_MINIMAP_EDITOR=77
OPEN_TRANSFER_EDITOR=82
TOOL_PICK=80
COPY=67
TOOL_ERASER=69
DEBUG_SHOW=290
PASTE=86
OPEN_BLOCK_EDITOR=74
TOOL_BUCKET=70
TOGGLE_INSPECTOR_MODE=73
TOGGLE_TRANSFERS=54
